### ISSUE TITLE
VRCOSC Media Chatbox format reset

### ISSUE THREAD

**Issue by WarmMillk** [VolcanicArts/VRCOSC#71] opened 2022-12-15 06:37 UTC
Whenever you close VRCOSC and reopen it, the text always resets back to the default(picture). It doesn't save your changes to it, and it only seems to be that option, all the rest save fine for me.
![image](https://user-images.githubusercontent.com/96452455/207789870-266460c5-9fd9-4469-a3d6-59c32fe22b1e.png)

**Comment by VolcanicArts** [comment] 2022-12-15 07:25
I'm not able to investigate right now but if you can post your `runtime.log` file located at `C:\Users\USER\AppData\Roaming\VRCOSC\logs` that would be handy.

What I'd suggest first is reinstalling the app to see if the issue persists.

If it does you can try clearing the module file as it might've corrupted. In the same place as the logs folder there's a `modules` folder which you can delete the `MediaModule.ini` file from and try to edit the format then.

**Comment by VolcanicArts** [comment] 2022-12-17 12:48
I've been able to reproduce the issue and it seems to be affecting only the media module. I'll update if I find a solution.

**Comment by VolcanicArts** [comment] 2022-12-17 13:08
Bug found. Small oversight with the way the settings lists were coded as if a settings list was empty it would cause the rest of the settings under it to not load. Bug never surfaced since most people leave the Start List alone.

This will be fixed in the next update.

**Closed by VolcanicArts** 2022-12-17 13:08 UTC
